### ISSUE TITLE
Refactoring test case to clear logic.

### ISSUE THREAD

**Issue by budougumi0617** [budougumi0617/EnglishWordQuizApp#8]
# Summary
It is redundant.
https://github.com/budougumi0617/EnglishWordQuizApp/blob/d2d7112fdd2311dd68281e2c8801417678306456/src/test/java/quiz/CheckMeanTest.java
```java
	@Test
	public void testNoSpaceMaxLength() {

		StringBuilder notOverSize = new StringBuilder();

		notOverSize.append("あいうえお");
		notOverSize.append("あいうえお");
		notOverSize.append("あいうえお");
		notOverSize.append("あいうえお");
		notOverSize.append("あいうえお");
```

# Priority
- [ ]  A
- [ ]  B
- [ ]  C
- [X]  Request

**Comment by budougumi0617** [comment]
@ema195y 
Easy way...
https://docs.oracle.com/javase/jp/8/docs/api/java/util/stream/IntStream.html#range-int-int-
```java
StringBuilder s = new StringBuilder();
IntStream.range(0, 50).forEach(i -> s.append("word"));
```

**Comment by ghost** [comment]
ffca6b7
